language: c
cache: ccache

before_install:
  - pwd
  - sudo mkdir -p -m 0755 /var/empty

matrix:
  include:
  - os: osx
    compiler: clang
    install:
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    - pip3 install nose rednose
    addons:
      homebrew:
        packages:
        - doxygen
        - ccache
        update: false
    env:
      - ARCH=x64
      - OPENSSL_DIR=/usr/local/opt/openssl

script:
  - set -eo pipefail
  - echo "Using GGC version:"
  - gcc --version
  - echo Running OpenSSH integration tests...
  - cd ${TRAVIS_BUILD_DIR}/integration/oqs_openssh && ./run_all.sh
  - echo Running OpenSSL integration tests...
  - cd ${TRAVIS_BUILD_DIR}/integration/oqs_openssl && ./run_all.sh
