name: Build and push Docker images

on:
  push:

jobs:
  #  ubuntu-arm64:
  #    strategy:
  #      matrix:
  #        distro:
  #          - focal
  #          - jammy
  #          - noble
  #    runs-on: oqs-arm64
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v4
  #      - name: Login
  #        uses: docker/login-action@v3
  #        with:
  #          username: ${{ vars.DOCKERHUB_USERNAME }}
  #          password: ${{ secrets.DOCKERHUB_TOKEN }}
  #      - name: Build and push arm64 tag
  #        #working-directory: ubuntu-${{ matrix.distro }}
  #        run: echo "Hello, world!"
  #          #uses: docker/build-push-action@v6
  #          #with:
  #          #push: true
  #          #tags: openquantumsafe/ci-ubuntu-${{ matrix.distro }}:latest-arm64

  ubuntu-x86_64:
    #needs: ubuntu-arm64
    strategy:
      matrix:
        distro:
          - focal
            #- jammy
            #- noble
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            #- name: Build and push x86_64 tag
            #uses: docker/build-push-action@v6
            #with:
            #push: true
            #build-args: ARCH=x86_64
            #tags: swilson4/ci-ubuntu-${{ matrix.distro }}:latest-x86_64
            #context: ubuntu-${{ matrix.distro }}
      - name: Combine images
        run: |
          docker manifest create swilson4/ci-ubuntu-${{ matrix.distro }}:latest \
            --amend openquantumsafe/ci-ubuntu-${{ matrix.distro }}:latest-x86_64 \
            --amend openquantumsafe/ci-ubuntu-${{ matrix.distro }}:latest-arm64 \
            #&& docker manifest push swilson4/ci-ubuntu-${{ matrix.distro }}:latest
